version: '3.8'

services:
  app:
    image: php:8.2-fpm  # Updated PHP version to 8.2
    container_name: app
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    ports:
      - "8000:80"
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    ports:
      - "8001:80"
    depends_on:
      - app

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
