# version: '3.8'

services:
  # PHP-FPM Service
  app:
    image: php:8.2-fpm  # Use the official PHP-FPM image
    container_name: app
    volumes:
      - .:/var/www/html  # Mount the current directory to the container's /var/www/html
    networks:
      - app-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=product_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
    ports:
      - "9000:9000"  # Expose PHP-FPM service on port 9000
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile  # Include a Dockerfile for the app service to build extensions

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - .:/var/www/html  # Mount the current directory to the container's /var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount your Nginx config
    networks:
      - app-network
    ports:
      - "8001:80"  # Expose Nginx service on port 8001
    depends_on:
      - app
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  # PostgreSQL Service
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data using Docker volumes

# Define networks for inter-service communication
networks:
  app-network:
    driver: bridge

# Define persistent storage volumes
volumes:
  pgdata:
    driver: local
