name: Laravel CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  static-analysis:
    name: Run PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer, phpstan

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=512M

  tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    needs: static-analysis

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testing_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user -d testing_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pdo, pdo_pgsql
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Set up environment file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: testing_db
          DB_USERNAME: user
          DB_PASSWORD: password
        run: php artisan migrate --force

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --testdox
